### ISSUE TITLE
Using Tab and TabPane

### ISSUE THREAD

**Issue by hoopes** [gadfly361/soda-ash#12]
Hi,

I was wondering if you had an example of using the Tab component. I can make it work using string content, but nothing else seems to take effect. For example:

    [sa/Tab
      {:renderActiveOnly false
       :panes [
        {:menuItem "Tab1" :pane { :key "tab1" :content "My Tab 1"}}}]

will create a single tab, and display `My Tab 1` in the content pane.

    [sa/Tab
      {:renderActiveOnly false
       :panes [
        {:menuItem "Tab1" :pane { :key "tab1" :content [sa/TabPane "My Tab 1"]}}}]

This will throw an error:
`Uncaught Error: Objects are not valid as a React child (found: object with keys {name, id, class}). If you meant to render a collection of children, use an array instead.`

This is using a function as my render.

    (defn tab-content [] "My Tab Content")
    [sa/Tab
      {:renderActiveOnly false
       :panes [
        {:menuItem "Tab1" :pane { :key "tab1" :content tab-content}}]

This will render the tab, but no content in it.

        {:menuItem "Tab1" :render tab-content}]

^ This gives a similar result. Also, returning a `TabPane` from `tab-content` leaves the content blank.

I've been over this for quite a while (or I wouldn't bother you with an issue). 

I *feel* like I'm doing the right thing, but obviously not, trying to follow https://react.semantic-ui.com/modules/tab/#types-basic

In reality, I'd like to use a reagent component as the content. I'm using `re-frame`, for whatever it's worth. 
If you have any insight or examples, I'll be much obliged. Thanks very much!

**Comment by gadfly361** [comment]
@hoopes Thanks for the detailed issue, much appreciated!

**Comment by gadfly361** [comment]
@hoopes Please try this

```clojure
   [sa/Tab
    {:renderActiveOnly false
     :panes
     [
      {:menuItem "Tab1"
       :pane
       {:key "tab1"
        :content
        (reagent/as-element [:span "Tab 1 content"])}
       }

      {:menuItem "Tab2"
       :pane
       {:key "tab2"
        :content
        (reagent/as-element [:span "Tab 2 content"])}
       }
      ]
     }]
```

**Comment by hoopes** [comment]
(ns my-ns
      (:require [reagent.core :as r]
                [soda-ash.core :as sa]))

    (defn- tab-content [some-obj]
      [sa/TabPane (str "Tab content! - " (:title @some-obj))])

    (defn main-panel [some-obj]
      [sa/Tab
       {:renderActiveOnly false
        :panes [
                {:menuItem "Tab"
                 :pane {:key "tab1"
                        :content (r/as-element [tab-content some-obj]) }}]}])

This did indeed work! So the `as-element` was needed b/c the react-semantic-ui expects react elements, but my previous try was...just reagent elements? Sorry, I'm just getting started with cljs. Is the `:>` thing not the same as `as-element`?

In any case, your help is super-appreciated, and this lib is great, thanks for it! Please feel free to close the issue, if you like.

**Comment by gadfly361** [comment]
@hoopes the `:>` is syntactic sugar for `adapt-react-class` which is close, but not quite the same thing. The difference is one is for a react component and the other is for a react element.

I haven't read this post, so forgive me if it is useless, but after a quick google search I found this:
https://tylermcginnis.com/react-elements-vs-react-components/

**Comment by gadfly361** [comment]
@hoopes I am going to close the issue, but feel free to ping me at clojurians slack in the #reagent channel. If you haven't you can sign up here: http://clojurians.net/
