### ISSUE TITLE
Name of the Menu Item

### ISSUE THREAD

**Issue by amarjeet000** [gadfly361/soda-ash#6]
1.
While using Menu Item, with the code below
`[sa/MenuItem {:name "Terms and Privacy"}]`

The expected name to be visible is "Terms and Privacy",
However, the actual result is "Terms **And** Privacy"
It is converting the first character of each word to uppercase. 

2.
No special characters, colon, etc are allowed
`[sa/MenuItem {:name "Rights: My Organizations"}]`
`[sa/MenuItem {:name "© My Organizations"}]`

Expected:  "Rights **:** My Organizations" and "**©** My Organizations"
Returns:  "Rights My Organizations" and "My Organizations"

Not sure if these are semantic-ui-react issue or soda-ash issue.

**Comment by gadfly361** [comment]
@amarjeet000 Thanks for asking! Unfortunately, this is caused upstream by Semantic UI React.  Soda-ash is a very thin layer to convert the react components to reagent and nothing extra.

From a cursory look at Semantic UI React, I think [this is the line of interest](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/collections/Menu/MenuItem.js#L135).

**Comment by amarjeet000** [comment]
Thanks @gadfly361 for prompt response. Yeah, I see the purpose of `name` key now. Had missed that.
