### ISSUE TITLE
Update semantic react to 0.79.1

### ISSUE THREAD

**Issue by ghost** [gadfly361/soda-ash#7]
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/CHANGELOG.md#v0790-2018-03-19

**Comment by gadfly361** [comment]
@allustin I have updated soda-ash to the most recent version of semantic ui react on cljsjs ... which is version 78.2.  I will leave this ticket open, but it will be blocked until someone updates semantic ui react on cljsjs.

**Comment by ghost** [comment]
@gadfly361 i will try update in cljs packages by myself - i find the instruction for that https://github.com/cljsjs/packages/wiki/Updating-packages

**Comment by ghost** [comment]
@gadfly361 my first step https://github.com/cljsjs/packages/pull/1587

**Comment by gadfly361** [comment]
@allustin Woot!

**Comment by gadfly361** [comment]
@allustin Just pushed a new version to clojars
