### ISSUE TITLE
How to pass a child component as a prop?

### ISSUE THREAD

**Issue by stoeckley** [gadfly361/soda-ash#8]
How to pass a Semantic component as an "element" in props, like here:

https://react.semantic-ui.com/elements/input#input-example-icon-element

I tried:

`[sa/Input {:icon [sa/Icon {:name "cancel" ...}] ... }]`

This nesting behavior and ability to pass components as props will probably come up occasionally but I cannot figure out the corresponding cljs syntax for it.

**Comment by gadfly361** [comment]
@astoeckley You are looding for `reagent/as-element`

```
[sa/Input {:icon (reagent/as-element [sa/Icon {:name "cancel"}])}]
```

**Comment by stoeckley** [comment]
thankx!
